version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  groups:
    opentelemetry:
      patterns:
      - "opentelemetry-*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
